apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app.notification" . }}-job
  labels:
  {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 60
  template:
    metadata:
      name: {{ include "app.fullname" . }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: post-install-job
          image: {{.Values.notificationService.image.repository}}
          imagePullPolicy: {{.Values.notificationService.image.pullPolicy}}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ template "app.fullname" . }}-secret
                  key: DATABASE_URL
          command:
            - sh
            - "-c"
            - php /tmp/app/bin/console doctrine:migrations:migrate --quiet