apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.delivery" . }}
  labels:
    name: {{ include "app.delivery" . }}
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deliveryService.type }}
  ports:
    - port: {{ .Values.deliveryService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ include "app.delivery" . }}
    {{- include "app.selectorLabels" . | nindent 4 }}
