apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-secret
  labels:
    app: {{ template "app.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DATABASE_URL: {{ printf "mysql://%s:%s@%s:%s/%s?appVersion=5.7" .Values.mysql.auth.username .Values.mysql.auth.password .Values.mysql.fullnameOverride (.Values.mysql.primary.service.port|toString) .Values.mysql.auth.database  | b64enc | quote }}
  KAFKA_URL: {{ printf "kafka://%s:%s"  .Values.kafka.fullnameOverride  (.Values.kafka.containerPorts.client | toString)  | b64enc | quote }}
  KAFKA_SASL_USERNAME: {{ printf "%s"  (first .Values.kafka.auth.sasl.jaas.clientUsers)  | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ printf "%s"  (default "" (first .Values.kafka.auth.sasl.jaas.clientPasswords | toString))  | b64enc | quote }}