apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-secret
  labels:
    app: {{ template "app.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  DATABASE_URL: {{ printf "mysql://%s:%s@%s:%s/%s?appVersion=5.7" .Values.mysql.auth.username .Values.mysql.auth.password .Values.mysql.fullnameOverride (.Values.mysql.primary.service.port|toString) .Values.mysql.auth.database  | b64enc | quote }}
  KAFKA_URL: {{ printf "%s:%s"  .Values.kafka.fullnameOverride  .Values.kafka.containerPorts.client  | b64enc | quote }}