apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "app.fullname" . }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi